steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-v', '/workspace:/usr/build', '-w', '/usr/build', 'maven:3.6.1-jdk-12', 'mvn', 'clean', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/site-controller:${TAG_NAME}', '--build-arg', 'ARTIFACT_VERSION=${TAG_NAME}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/site-controller:${TAG_NAME}']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment
      - site-controller
      - site-controller=gcr.io/${PROJECT_ID}/site-controller:${TAG_NAME}
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
images: ['gcr.io/${PROJECT_ID}/site-controller:${TAG_NAME}']
